I'm sorry, but an uncaught exception occurred.

While running game code:
  File "game/first_task.rpy", line 38, in script
    $change_skill(1, True)
  File "game/first_task.rpy", line 38, in <module>
    $change_skill(1, True)
NameError: name 'change_skill' is not defined

-- Full Traceback ------------------------------------------------------------

Full traceback:
  File "game/first_task.rpy", line 38, in script
    $change_skill(1, True)
  File "E:\renpy\renpy-8.0.3-sdk\renpy\ast.py", line 1131, in execute
    renpy.python.py_exec_bytecode(self.code.bytecode, self.hide, store=self.store)
  File "E:\renpy\renpy-8.0.3-sdk\renpy\python.py", line 1061, in py_exec_bytecode
    exec(bytecode, globals, locals)
  File "game/first_task.rpy", line 38, in <module>
    $change_skill(1, True)
NameError: name 'change_skill' is not defined

Windows-10-10.0.17763 AMD64
Ren'Py 8.0.3.22090809
Пушистые IT 0.0
Sat Nov 26 15:49:22 2022
